meta_product_name:  "Tristan Viney's full stack Ruby on Rails developer portfolio"

meta_title:         'Tristan Viney: creative problem solver meets full stack Ruby on Rails developer'

meta_description:   'I’ve combined my 7+ years advertising experience with a
                    full stack Ruby on Rails skillset — to help brands solve
                    challenging problems and build interesting products.'

meta_image:         'tristan.jpg'

twitter_account:    '@tristanviney'
